### ISSUE TITLE
Ajouter un bash pour interagir directement avec le système sans passer par le SSH

### ISSUE THREAD

**Issue by DjLeChuck** [DjLeChuck/recalbox-manager#12]

**Comment by DjLeChuck** [comment]
Semble impossible sans passer par un logiciel côté serveur... Ce qui n'est pas désiré.

**Comment by DjLeChuck** [comment]
https://github.com/sourcelair/xterm.js

**Comment by MikaXII** [comment]
Je pense que ce module sera mieux adapté à ce que tu veux : https://github.com/mscdex/ssh2
Donc tu peux faire un client ssh directement sur une page web, par contre ce n'est pas à mon goût une feature indispensable pour le moment.
