### ISSUE TITLE
Évolution : afficher start ou stop de ES selon l'état de ES

### ISSUE THREAD

**Issue by substring** [DjLeChuck/recalbox-manager#20]
ouais la je chipote :smile:

**Comment by MikaXII** [comment]
"affichier" ?
Message caché ? ^^

**Comment by DjLeChuck** [comment]
Ouais, les demandes du @substring me font chier :angel: :heart: 

En plus je ne suis pas sûr de pouvoir faire ça "proprement".

**Comment by substring** [comment]
ben en shell : `/etc/init.d/S31emulationstation status`
