### ISSUE TITLE
Bugz pre beta5

### ISSUE THREAD

**Issue by substring** [DjLeChuck/recalbox-manager#25]
- URL virtual gamepad et clavier : ne pas mettre en dur http://recalbox:8080 parce que :
  - http://recalbox/ ne marche sur windows. Mac et Linux c'est http://recalbox.local
  - recalbox, c'est le hostname defini dans l'os et il peut se changer facilement notammet par le manager (utile quand on a plusieurs recalbox chez soit)
- monitoring : un core toujours a 100% alors que top ne montre rien de tel. Ou alors nodejs est vraiment gourmand
- Audio : ok :+1:  (pas vérifié si les valeurs enregistrées sont les bonnes dans cette version , mais avant elles l'etaient)
- BIOS : peut-etre renommer la colonne "Options" pour "action"
- Configuration : me semble que par defaut la timzone c'est Paris ... peut etre a caler sur la langue du navigateur si ce n'est pas renseigné, parce que sauver la page mettra USA partout
- ROMS : impossible d'editer les données de la ROM SNES fourie par defaut (le remake de donkey kong) alors que la ROM est scrapée. Pas de pb pour les autres systemes avec leurs roms par defaut

Je n'ai pas vérifié la regression de ce qui marchait avant ;)

**Comment by DjLeChuck** [comment]
Voilà tout est corrigé, hormis le monitoring.

Je clos @substring ?

**Comment by substring** [comment]
Yes :+1:

**Comment by rockaddicted** [comment]
Quel homme...

Le sam. 28 janv. 2017 08:52, Vivien DE BONA <notifications@github.com> a
écrit :

**Comment by DjLeChuck** [comment]
Je suis trop fort. ;-)
