### ISSUE TITLE
Ajouter les nouvelles options de configuration

### ISSUE THREAD

**Issue by DjLeChuck** [DjLeChuck/recalbox-manager#28]
* RetroAchievements : mode hardcore
* wifi : connexions 2 et 3

d'autres non vue encore ?

**Comment by rockaddicted** [comment]
Hello, si celles ci ne sont pas encore prises en compte, alors oui.
https://github.com/recalbox/recalbox-buildroot/blob/master/package/recalbox-system/rpi3/recalbox.conf#L42
```
### Select a system to show on boot (use rom directory name) (string)
system.es.selectedsystem=favorites
### Show the gamelist of the first or selected system on boot (0,1)
system.es.bootongamelist=0
### Disable system view ES will boot and show ONLY the first or selected system (0,1)
system.es.hidesystemview=0
```

**Comment by DjLeChuck** [comment]
Fait sur le nouveau manager.
