### ISSUE TITLE
Upload screenshot in ROM management from web

### ISSUE THREAD

**Issue by pillabichos** [DjLeChuck/recalbox-manager#30]
The new ROM management allows to edit data about a ROM but there some thing may be improvement:
- Allow upload an image, screenshot or cover.
- Respect the information supplied by local user when rescraped.
- Allow upload and complete some databases (f.e.: screenscraper) suggesting your own information.

**Comment by DjLeChuck** [comment]
Upload an image is in my TODO list! 

What did you mean by _Respect the information_?
And what about _Allow upload_? Upload what?

**Comment by pillabichos** [comment]
Respect the information means that if I add some information about a ROM from the web browser in recalbox.local and I select scrape, I lost the previous information added.
I'd like to upload an image of the ROM from http://recalbox.local, this image could be a cover of the cassette / cartridge, a screenshot or both.

**Comment by DjLeChuck** [comment]
I'm afraid I can't do anything about this. Scrapping softwares works on their own and don't care about existing data (except if there is an option for that).

The best is to scrap your library then use the manager to update informations.

---

For upload you means upload your informations into external databases like screenscraper?

**Comment by pillabichos** [comment]
No, I'd like to upload from my PC to my raspberry pi using your web interface.
I show an image about what I'd like to do.
![web interface](https://cloud.githubusercontent.com/assets/25672982/23397504/178dec3a-fd99-11e6-98fd-0983e980b53c.png)

**Comment by DjLeChuck** [comment]
Yes I understand this need. As I said it's in my TODO list. :)

You have mentioned 3 points in your first post:
* **Allow upload an image, screenshot or cover.** -> That's what we are speaking about, upload an image from the manager, it will be done
* **Respect the information supplied by local user when rescraped.** -> I can't do anything as said previously
* **Allow upload and complete some databases (f.e.: screenscraper) suggesting your own information.** -> That's what I don't understand.

Sorry for my misunderstanding!

**Comment by pillabichos** [comment]
I explain bad because English in not my mother tongue and there a lot of things difficult to explain.
 
Thanks for your effort

**Comment by DjLeChuck** [comment]
And it's not mine too!

But I understand the most important. :)
