### ISSUE TITLE
Lost language configuration in web

### ISSUE THREAD

**Issue by pillabichos** [DjLeChuck/recalbox-manager#31]
I always see the web interface in French, although I select another language.
I'm using in latest recalbox in raspberry pi 2.

**Comment by DjLeChuck** [comment]
The i18n component use your browser local storage or cookies to save the selected language between sessions.
Could you see if one of these are used?

**Comment by DjLeChuck** [comment]
Ok my bad, the "bug" is simple: translations files are not in the manager... I make a mistake that will be fix for the next release of my manager (ping @substring)
