### ISSUE TITLE
Coeur n'est pas traduit

### ISSUE THREAD

**Issue by substring** [DjLeChuck/recalbox-manager#36]
Cf https://github.com/DjLeChuck/recalbox-manager/blob/71af0613d7ef155d1a2a74cbe5411da122af8a92/client/src/components/Monitoring.js#L69

**Comment by DjLeChuck** [comment]
Est-ce utile de le traduire ? Je suis toujours dans l'optique de retirer ce bloc qui donne des résultats faux.

**Comment by substring** [comment]
C'est vous qui voyez ...

**Comment by DjLeChuck** [comment]
Personnellement, je n'en vois pas l'utilité je n'utilise pas cette page. Cependant, je l'ai reprise car elle était sur l'ancien manager, j'imagine qu'elle n'était pas là par hasard ?

**Comment by substring** [comment]
C'était bien avant mon avènement !
