### ISSUE TITLE
Retrait des options liées à xboxdrv

### ISSUE THREAD

**Issue by rockaddicted** [DjLeChuck/recalbox-manager#37]
Hello, en 4.1, le pilote xboxdrv n'est plus présent dans système.
Serait il possible de retire du manager les options concernant ce dernier.

**Comment by DjLeChuck** [comment]
Déjà fait : https://github.com/DjLeChuck/recalbox-manager/commit/fdaf1bc1aa76ca1fb3fdd2d80779d4d1a82a9423 et https://github.com/DjLeChuck/recalbox-manager/commit/71ac518a10d0f6f265fcbaac305086cccecbbedf
