### ISSUE TITLE
Impossible d'arreter ou redemarrer ES par le manager

### ISSUE THREAD

**Issue by substring** [DjLeChuck/recalbox-manager#44]
Issue reportée par des users, que je viens de vérifier avec le dernier commit.

Restart et Stop ne marchent pas, par contre Start oui. Aucune erreur n'apparait sur la console serveur quand j'utilise un des boutons qui déconne.

**Comment by DjLeChuck** [comment]
La version proposée aux utilisateurs est laquelle (même si toi tu as testé avec le dernier commit) ?

**Comment by substring** [comment]
la 2-0-beta

**Comment by DjLeChuck** [comment]
Ha ok je suis en retard sur ma borne alors !

Je corrigerais cela, mettrais à jour les langues, et ferais une 2.0.1 car il y a eu qqs corrections depuis.

**Comment by substring** [comment]
Tu devances ma prochaine question pour une release ^^

**Comment by DjLeChuck** [comment]
- [ ] Vérifier l'arrêt / le redémarrage d'ES
- [ ] Lors de l'arrêt, renvoyer vers une page disant "Bye bye le manager ne va plus fonctionner car recalbox est éteint"
- [ ] Lors du redémarrage, renvoyer vers une page disant "Wait mon petit le manager va être indisponible le temps du redémarrage"
