### ISSUE TITLE
La version 2.0.1 affiche 2.0.0 dans la barre e bas a gauche

### ISSUE THREAD

**Issue by substring** [DjLeChuck/recalbox-manager#45]
C'est bien un v2.0.0 qui s'affiche alors qu'on est en 2.0.1 (bugs de la 2.0.0 résolus d'ailleurs)

**Comment by DjLeChuck** [comment]
Quel débile en effet alors que j'm'étais dit de SURTOUT ne pas oublier de la changer... --'

**Comment by DjLeChuck** [comment]
Corrigé : cdbd028
