### ISSUE TITLE
2.0.1 : les drapeaux de langues ne s'affichent plus :(

### ISSUE THREAD

**Issue by substring** [DjLeChuck/recalbox-manager#46]
cf titre

**Comment by DjLeChuck** [comment]
Ils ont été retirés, trop chiant et certains manquaient dans la collection que j'avais. Et puis il paraît que c'est pas bien de représenter une langue par un drapeau. 👎

**Comment by substring** [comment]
osef les bonnes pratiques ;) mais si c'est volontaire, ok !
