### ISSUE TITLE
recalbox manager 2 inaccessible

### ISSUE THREAD

**Issue by Ephagor** [DjLeChuck/recalbox-manager#50]
Bonjour, 
lorsque je choisi la version 2 du web manager de recalbox, je ne peux pas y accéder via mon navigateur ( chrome)

> ERR_CONNECTION_REFUSED

alors si je remet la version 1 dans le fichier de conf, je peux y accéder sans problème. 
quelqu'un à une idée ?

Merci d'avance.

**Comment by DjLeChuck** [comment]
Bonsoir,

Désolé pour le long délai d'attente. 
Maintenant que la 4.1 est sortie, as-tu réussi à te connecter ou as-tu toujours le même problème ?

**Comment by Ephagor** [comment]
bonjour, 
 je l'ai désinstallé depuis car j'avai besoin de mon Pi pour un autre usage).
j'ai un autre PI en attente de livraison pour remettre recalBox.
A suivre

**Comment by DjLeChuck** [comment]
Hellon

Ok très bien !
Je laisse le ticket ouvert au cas où. N'hésite pas à revenir quand tu auras testé de nouveau !
