### ISSUE TITLE
[4.1] Gamepad has own index page

### ISSUE THREAD

**Issue by robsdedude** [DjLeChuck/recalbox-manager#51]
Recalbox 4.1 will be shipped with a version of the virtualgamepad app that has its own index page on which one can choose between gamepad, keyboard, and touchpad.
Thus, the direct link to the keyboard might not be necessary anymore.

**Comment by DjLeChuck** [comment]
fix with 7db270bcb039377b2c355b96dd7573e2e6cff11a

**Comment by robsdedude** [comment]
merci
