### ISSUE TITLE
German translation of "core" missing/broken

### ISSUE THREAD

**Issue by robsdedude** [DjLeChuck/recalbox-manager#53]
![missing translation](https://user-images.githubusercontent.com/4061254/31021795-3bca4760-a537-11e7-9457-1a70bc381b09.png)

**Comment by rockaddicted** [comment]
recalbox-manager's translation is managed by poeditor: https://poeditor.com/join/project/taFNFlZ840

**Comment by robsdedude** [comment]
Alright. I opened #54 to mention this in the README.
