### ISSUE TITLE
Can't stop emulationstation from manager

### ISSUE THREAD

**Issue by rockaddicted** [DjLeChuck/recalbox-manager#56]
We can start and restart emulationstation from the manager, but we can't stop it.
Could be a good thing to be able to do that without open a ssh session.

**Comment by DjLeChuck** [comment]
Normally, the button changes itself depending on the ES status.

Can you look at XHR requests in your browser and tel me the result? A request is done every 3 seconds.

**Comment by cpcbegin** [comment]
It always shows the button as 'iniciar' (start).
I try with Firefox and chromium in Debian and Google Chrome in Android en Spanish locales.

**Comment by OyyoDams** [comment]
Take a look at my pull request suggestion ;)
