### ISSUE TITLE
Manager don't like when you erase bios readme.txt

### ISSUE THREAD

**Issue by rockaddicted** [DjLeChuck/recalbox-manager#57]
Manager is using the bios readme.txt file to check files hashes.
So, if user erase the readme.txt file inside bios folder, the manager display a white page with a "waiting wheel".
Could be a good thing to display a message instead of this page.

**Comment by substring** [comment]
use the one from the share_init ?

**Comment by rockaddicted** [comment]
:+1: 
This one on `share` is not updated during upgrade. contrary to that one on `share_init`.
So guys doing an upgrade don't have bios checking of new added systems.
