### ISSUE TITLE
[Feature Request] Make it possible to test several hashes for 1 BIOS file

### ISSUE THREAD

**Issue by substring** [DjLeChuck/recalbox-manager#58]
Some systemhave only 1 possible bios, some others may have many (PSX, Dreamcast, Neogeo ...). The manager should be able to handle when there are several hashes for a bios file and report accordingly.

**Comment by rockaddicted** [comment]
https://github.com/DjLeChuck/recalbox-manager/issues/3#issuecomment-336648050

**Comment by DjLeChuck** [comment]
Doublon du coup, donc je clos.
Si plus de détails à fournir indique-le dans le ticket #3
