### ISSUE TITLE
Update recalbox.conf parameters

### ISSUE THREAD

**Issue by paradadf** [DjLeChuck/recalbox-manager#67]
Update recalbox.conf existing parameters instead of escaping them (the old ones) and adding the new to the bottom.

**Comment by DjLeChuck** [comment]
I'm using a recalbox script to update the configuration file, so I can't do anything: https://github.com/DjLeChuck/recalbox-manager/blob/master/src/routes/save.js#L26

@substring maybe an idea?

**Comment by substring** [comment]
This python script doesn't comment, but uses sed : https://gitlab.com/recalbox/recalbox-configgen/blob/master/configgen/settings/recalboxSettings.py#L24

@paradadf was that error happening when you were trying to change your timezone ?

**Comment by paradadf** [comment]
Yes! It should just repöace the timezone instead of writting stuff on the bottom.
