### ISSUE TITLE
Please update Russian localization

### ISSUE THREAD

**Issue by bootloader24** [DjLeChuck/recalbox-manager#74]
Russian translation is corrected and updated. Please merge it from the Poeditor.com!

**Comment by DjLeChuck** [comment]
Thank you for your work I will update it tomorrow, then we'll have to wait for the next update of recalbox! 👍

**Comment by DjLeChuck** [comment]
Fix with 9c5e7adb1129c9eedaf8f5d310f79fd87d73027d
