### ISSUE TITLE
Error when loading ROM list

### ISSUE THREAD

**Issue by facundoolano** [DjLeChuck/recalbox-manager#77]
When entering the ROM list of some of the systems (but not all of them), the page stucks with the loading spinner.

The devtools shows a 500 error in one of the ajax calls:

```
Request URL: http://192.168.1.15/get?option=romsList&params=system=snes,subpath=
Request method: GET
Remote address: 192.168.1.15:80
Status code: 500
Response:
{"message":"Path must be a string. Received [ './downloaded_images/Batman (Proto)-image.png', '' ]","errors":{}}
```

**Comment by facundoolano** [comment]
This can be patched by adding this

```js
if (Array.isArray(value)) {
  value = value[0];
}
``` 

before [this line](https://github.com/DjLeChuck/recalbox-manager/blob/master/src/routes/get.js#L110).

If that patch is good enough I can send a PR with it.

**Comment by DjLeChuck** [comment]
Thank you, you can send the PR!
